version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    # Run it at a specific time so that we don't get emails all day long
    time: "00:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "*"
    # GitHub actions are using git tags (v1 = v1.2 = v1.2.3) which should be compatible until a major change is performed
    update-types: 
    - "version-update:semver-minor"
    - "version-update:semver-patch"
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    # Run it at a specific time so that we don't get emails all day long
    time: "00:00"
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: "jakarta.persistence:jakarta.persistence-api"
    versions: ">=3.1.0"
  - dependency-name: "jakarta.validation:jakarta.validation-api"
    versions: ">=3.1.0"
  - dependency-name: "jakarta.el:jakarta.el-api"
    versions: ">=6.0.0"
  - dependency-name: "jakarta.servlet:jakarta.servlet-api"
    versions: ">=6.0.0"
